from llama_index.core.agent.workflow import FunctionAgent
from typing import Literal, Annotated
import aiohttp
from workflow_config.default_settings import Settings

#
# MWB sub-agent specializing in one of seven context areas of the MWB REST API
#

context = "metstat"

# Annotated tool specifically for formulating a metstat endpoint
async def call_metstat_endpoint(
    ANALYSIS_TYPE: Annotated[
        Literal[
            '', 
            'MS', 
            'LCMS', 
            'GCMS',
            'NMR'
],
        """Refers to the analytical method used in metabolomics studies. It can take one of the following values: 
        '': If analysis type is not specified by user then return an empty string.
        MS: Return all studies with any mass spectrometry techniques.
        LCMS: Liquid Chromatography-Mass Spectrometry analysis technique.
        GCMS: Gas Chromatography Mass Spectrometry analysis technique.
        NMR: Nuclear Magnetic Resonance analysis technique."""
    ] = '',
    POLARITY: Annotated[
        Literal[
            '', 
            'POSITIVE', 
            'NEGATIVE'
    ],
        "Refers to the Mass Spectrometry (MS) ion mode used in the analysis. If not specified then return an empty string ''."
    ] = '',
    CHROMATOGRAPHY: Annotated[
        Literal[
            '', 
            'Reversed phase', 
            'Normal phase', 
            'HILIC', 
            'GC', 
            'Phenyl', 
            'None'
        ],
        """Chromatographic separation used in the analysis. It can take one of the following values: 
        '': If analysis type is not specified by user then return an empty string.
        Reversed phase: 
        Normal phase:
        HILIC: Hydrophilic Interaction Liquid Chromatography.
        GC: Gas Chromatography - this is a distinct parameter separate from analysis type parameter GCMS.
        Phenyl:
        None:"""
    ] = '',
    SPECIES: Literal[           
                     '',
                    'Abiotic',
                    'Acinetobacter',
                    'Acinetobacter baumannii',
                    'Acropora cervicornis',
                    'Algae',
                    'Ant',
                    'Apple',
                    'apple, pear',
                    'Arabidopsis thaliana',
                    'Athorix',
                    'Aurantiochytrium limacinum',
                    'Auxenochlorella',
                    'Baboon',
                    'Bacillus cereus',
                    'Bacillus megaterium',
                    'Bacillus subtilis',
                    'Bacteria',
                    'Bacteroides',
                    'Bacteroides fragilis',
                    'Bacteroides ovatus',
                    'Bacteroides thetaiotaomicron',
                    'Bacteroides uniformis',
                    'Banana',
                    'Barley',
                    'Basil',
                    'Beet',
                    'Bermudagrass',
                    'Bighorn sheep',
                    'Black flying fox fruit bat',
                    'Black mustard',
                    'Blautia producta',
                    'Blood parasite',
                    'Brine shrimp',
                    'Cabbage',
                    'Candida albicans',
                    'Capybara',
                    'Carrot',
                    'Cassiopea andromeda',
                    'Cat',
                    'Cattle',
                    'C. difficile',
                    'C. elegans',
                    'Chicken',
                    'Chickpea',
                    'Chili pepper',
                    'Chlamydomonas reinhardtii',
                    'Chlorella',
                    'Clostridium clostridioforme',
                    'Clostridium hathewayi',
                    'Clostridium hylemonae',
                    'Clostridium scindens',
                    'Clostridium symbiosum',
                    'Common bean',
                    'Common prawn',
                    'Cordyceps',
                    'Corydalis yanhusuo',
                    'Cow',
                    'Crab',
                    'Crayfish',
                    'Cryptococcus neoformans',
                    'Date palm',
                    'Dog',
                    'Dolphin',
                    'E. coli',
                    'Eggerthella lenta',
                    'Enterococcus faecalis',
                    'Enterococcus faecium',
                    'Enterococcus hirae',
                    'Escherichia fergusonii',
                    'European pepper moth',
                    'Exaiptasia diaphana',
                    'Exidia glandulosa',
                    'Fish',
                    'Flavonifractor plautii',
                    'Flesh Fly',
                    'Fragilariopsis cylindrus',
                    'Frog',
                    'Fruit fly',
                    'Fungi',
                    'Fusobacterium nucleatum',
                    'Garlic',
                    'Ginger',
                    'Goat',
                    'Grass',
                    'Guinea Grass',
                    'Habanero pepper',
                    'Haemophilus influenzae',
                    'Hamster',
                    'Heart-leaved poison',
                    'Holly oak',
                    'Honey bee',
                    'Honey Bee',
                    'Horse',
                    'Human',
                    'Ilyonectria estremocensis',
                    'Ilyonectria mors-panacis',
                    'Ilyonectria robusta',
                    'Ilyonectria rufa',
                    'Ilyonectria torresensis',
                    'Lake water',
                    'Lentilactobacillus kefiri',
                    'Lettuce',
                    'Little brown bat',
                    'Macaque monkey',
                    'Maize',
                    'Malaysian red seaweed',
                    'Marine microbes',
                    'Marine plankton',
                    'Marmoset',
                    'Mayfly',
                    'Methanococcus maripaludis',
                    'Microchloropsis gaditana',
                    'Mosquito',
                    'Moss',
                    'Mouse',
                    'Mucidula mucida',
                    'Nannochloropsis',
                    'Navicula cf. perminuta',
                    'Neonectria obtusispora',
                    'Nitzschia lecointei',
                    'Oat',
                    'Olive',
                    'Onion',
                    'Ophiocordyceps',
                    'Pacific Abalone',
                    'Panax ginseng',
                    'Parabacteroides distasonis',
                    'Peach',
                    'Pear',
                    'Pendant amaranth',
                    'Phaeodactylum tricornutum',
                    'Phytoplankton',
                    'Picochlorum celeri',
                    'Pig',
                    'Pine',
                    'Plankton',
                    'Plant',
                    'Plants',
                    'Plasmodium berghei',
                    'Plasmodium falciparum',
                    'Porphyromonas',
                    'Potato',
                    'Propionibacterium',
                    'Pseudomonas aeruginosa',
                    'Rabbit',
                    'Rainbow trout',
                    'Rapeseed',
                    'Rat',
                    'Rhesus monkey',
                    'Rice',
                    'Rickettsia parkeri',
                    'Rothia',
                    'Rubber tree',
                    'Ruegeria pomeroyi',
                    'Sage',
                    'Salmonella',
                    'Seal',
                    'Seawater',
                    'Sheep',
                    'Sinorhizobium',
                    'Soybean',
                    'Spinach',
                    'Squirrel',
                    'Staphylococcus aureus',
                    'Staphylococcus epidermidis',
                    'Strawberry',
                    'Streptococcus',
                    'Streptococcus pyogenes',
                    'Stylophora pistillata',
                    'Sugarcane',
                    'Sugar Maple',
                    'Sulfolobus acidocaldarius',
                    'SUlfolobus acidocaldarius',
                    'Sulfolobus islandicus',
                    'Symbiodiniaceae',
                    'Synechococcus',
                    'Synechococcus elongatus',
                    'Synthetic',
                    'Thalassiosira pseudonana',
                    'Thermococcus kodakarensis',
                    'Thermococcus sp. AM4',
                    'Tobacco',
                    'Tomato',
                    'Toxoplasma gondii',
                    'Treponema',
                    'Trypanosoma brucei',
                    'V. cholerae',
                    'Veillonella parvula',
                    'Vine',
                    'Western clawed frog',
                    'Wheat',
                    'Yeast',
                    'Yew',
                    'Zebrafish'
            ] = '',
    SAMPLE_SOURCE: Annotated[
        Literal[
            '',
            'Adipose tissue',
            'Adrenal gland',
            'Algae',
            'AML cells',
            'Amniotic fluid',
            'Anther',
            'Aortic valve tissue',
            'Arteries',
            'Astrocyte cells',
            'Atria',
            'Back of Eye',
            'Bacterial cells',
            'Bacterial media',
            'BAT',
            'B-cells',
            'Bee heads',
            'Biofilm',
            'Biopsy',
            'Bladder',
            'Blood',
            'Blubber',
            'Bone',
            'Bone marrow',
            'Bovine meat',
            'Brain',
            'Brain Cancer Cells',
            'Brain cortex',
            'Brain organoids',
            'Brainstem',
            'Breast',
            'Breast cancer cells',
            'Breast milk',
            'Breast tissue',
            'Breath',
            'Brown adipose',
            'Capsicum Chinense',
            'Cardiomyocyte cells',
            'Cecal content',
            'Cecum',
            'Cells',
            'Cerebrospinal fluid',
            'Chow diet',
            'CNS',
            'Colon',
            'Colonic mucosa',
            'Colorectal Cancer Cells',
            'Corpus Luteum',
            'Cortex',
            'CSF',
            'Cultured cells',
            'Culture media',
            'Cyst fluid',
            'Date palm fruit',
            'Diaphragm',
            'Diatom cells',
            'Diet',
            'Dorsal Root Ganglia',
            'DSI',
            'Duodenum',
            'Eggs',
            'Embryonic cells',
            'Endothelial cells',
            'Epididymal fat',
            'Epithelial cells',
            'Epithelial lining fluid',
            'Erythrocytes',
            'Esophagus',
            'Eye tissue',
            'Feces',
            'Fibroblast cells',
            'Fish larvae',
            'Flushing',
            'Fly',
            'Fly Head',
            'Follicular fluid',
            'Food',
            'Foreskin',
            'Fruit',
            'Fungal cells',
            'Fungus',
            'Galea',
            'Gallbladder',
            'Gastrocnemius',
            'Glioma cells',
            'gWAT',
            'Head tissue',
            'Heart',
            'HEK cells',
            'HeLa cells',
            'Hemolymph',
            'Hepatopancreas',
            'Hep G2 cells',
            'Hippocampus',
            'Human tissue',
            'Hypothalamus',
            'Ileum',
            'Infected Red Blood Cells',
            'Insect tissue',
            'Interstitial fluid',
            'Intestine',
            'Intracellular Granulocyte',
            'iPSC cells',
            'Jejunum',
            'Keratinocytes',
            'Kidney',
            'Larvae',
            'Latex',
            'Leaf',
            'Leukemia cells',
            'Liver',
            'Liver Cancer Cell Line',
            'LNCaP cells',
            'Lung',
            'Lung Tumors',
            'Lymph fluid',
            'Lymph node',
            'Lymphoma cells',
            'Macrophages',
            'Maize kernel',
            'Maize starchy endosperm',
            'Marine particulate matter',
            'Media',
            'Merozoites',
            'Mesenteric lymph',
            'Microglia',
            'Milk',
            'Minimal cell JCVI-syn3B',
            'Mitochondria',
            'Mononuclear cells',
            'Mouse tissue',
            'MSI',
            'Multiple tissues',
            'Muscle',
            'Mycoplasma mycoides',
            'Myotubes',
            'Nasal Polyp tissue',
            'Neurons',
            'Neurospheres',
            'Neutrophils',
            'Nucleus accumbens',
            'Optic nerve',
            'Ovarian cancer cells',
            'Ovaries',
            'Pancreas',
            'Parasite',
            'Peritoneal fluid',
            'PJI Tissue',
            'Placenta',
            'Plankton',
            'Plant',
            'Plant Leaves and Roots',
            'Plaque samples',
            'Plasmodium cells',
            'Pooled sample',
            'Prostate',
            'Prostate cancer cells',
            'Proximal tubular cells',
            'PSI',
            'Quadriceps',
            'Rectum',
            'Retina',
            'Rhizome',
            'Rhizosphere',
            'Ribonucleic acid',
            'Roots',
            'Saliva',
            'Sarcoma',
            'Scalp',
            'Seaweed',
            'Seedlings',
            'Seeds',
            'Shrimp organs',
            'SI',
            'SIHUMIx',
            'Skeleton',
            'Skin',
            'Small intestine',
            'Smooth muscle',
            'Soil',
            'Spermatozoa',
            'Spinal cord',
            'Spleen',
            'Splenocytes',
            'Sputum',
            'Standard phosphatidylcholines',
            'Stem cells',
            'Stomach',
            'Stool',
            'Subcutaneous fat',
            'Suspended Marine Particulate Matter',
            'Sweat',
            'Synthetic',
            'Tail',
            'T-cells',
            'T-Cells',
            'Tear',
            'Testes',
            'Thyroid',
            'Tissue',
            'Tongue',
            'Tritrichomonas musculis cells',
            'Tumor allograft',
            'Tumor cells',
            'Tumor interstitial fluid',
            'Tumor tissue',
            'Ulcer biopsies',
            'Umbilical cord plasma',
            'Unspecified',
            'Urine',
            'Uterine fluid',
            'Uterus',
            'Vaginal epithelium',
            'Vascular smooth muscle cells',
            'Vastus lateralis',
            'Vena cava',
            'Ventricles',
            'Vitreous',
            'Water',
            'White adipose',
            'Whole animals',
            'Whole insect',
            'Whole Tissue',
            'Whole tumor',
            'Wine',
            'Worms',
            'Yeast cells'
 ],
        "Study sample biological materials or tissues used in the analysis."
    ] = '',
    DISEASE: Literal[
        '',
        'Abdominal aortic aneurysm',
        'Abiotic stress',
        'Acute kidney injury',
        'Acute respiratory distress syndrome',
        'Addiction',
        'Adrenoleukodystrophy',
        'Alcoholism',
        'Alkaptonuria',
        'Allergy',
        'Alopecia',
        'ALS',
        'Alzheimers disease',
        'Alzheimer’s Disease',
        'Anemia',
        'Angina',
        'Anorexia nervosa',
        'Antibiotic resistance',
        'Anxiety',
        'Arthralgia',
        'Arthritis',
        'Asthma',
        'Atherosclerosis',
        'Atrial fibrillation',
        'Autism',
        'Autoimmune disease',
        'Bacterial infection',
        'Bipolar disorder',
        'Bipolar I Disorder',
        'Brain disease',
        'Cachexia',
        'Cancer',
        'Cardiomyopathy',
        'Cardiovascular disease',
        'Cerebellar ataxia',
        'Chronic fatigue syndrome',
        'Chronic kidney disease',
        'Chronic stress',
        'Circadian Rhythm Disorder',
        'Clubroot disease',
        'Cognitive impairment',
        'Colitis',
        'COPD',
        'COVID-19',
        'Crohns disease',
        'Cystic fibrosis',
        'Dementia',
        'Dental erosion',
        'Dental plaque',
        'Depression',
        'Dermatitis',
        'Diabetes',
        'Diabetes, Cardiovascular Disease',
        'DNA damage response',
        'Down syndrome',
        'Drug addiction',
        'Duchenne Muscular Dystrophy',
        'Eczema',
        'Endotoxemia',
        'Enterocolitis',
        'Environmental exposure',
        'Epilepsy',
        'Eye disease',
        'Fatty liver disease',
        'Ferroptosis',
        'Fibrosis',
        'Friedreichs Ataxia',
        'Fungal infection',
        'Gastrointestinal disease',
        'Genetic disease',
        'Giardia infection',
        'Glaucoma',
        'GLUT1 Deficiency Syndrome',
        'Graft versus host disease',
        'Halitosis',
        'Heart disease',
        'Heart injury',
        'HIV',
        'Hypercortisolemia',
        'Hyperglycemia',
        'Hyperlipidemia',
        'Hypertension',
        'Hypoglycemia',
        'Hypospadias',
        'Hypoxia',
        'Immune system disorders',
        'Infection',
        'Infertility',
        'Inflammation',
        'Inflammatory bowel disease',
        'Influenza',
        'Interstitial cystitis',
        'Irritable bowel syndrome',
        'Ischemia',
        'Kidney disease',
        'Krabbe disease',
        'Leigh syndrome',
        'Leprosy',
        'Liver Damage',
        'Liver disease',
        'Liver disease; Environmental exposure',
        'Liver failure',
        'Lung disease',
        'Lung Disease',
        'Lung injury',
        'Lupus',
        'Lupus nephritis',
        'Lyme disease',
        'Malaria',
        'Malnutrition',
        'Maternal Hypoxemia',
        'Maternal immune system activation',
        'Melioidosis',
        'Meningitis',
        'Meningoencephalitis',
        'Metabolic disease',
        'Metabolic Disorders',
        'Metabolic syndrome',
        'Mitochondrial disease',
        'Mosaic virus infection',
        'Multiple sclerosis',
        'Muscular dystrophy',
        'Musculoskeletal system disease',
        'Myalgic encephalomyelitis/chronic fatigue syndrome',
        'Myopathy',
        'NASH',
        'Necrotizing soft-tissue infections',
        'Neurodegenerative disease',
        'Neuropathy',
        'Obesity',
        'Organ transplantation',
        'Osteoarthritis',
        'Osteoporosis',
        'Oxidative stress',
        'Ozone Stress',
        'Parasitic infection',
        'Parkinsons disease',
        'Peanut allergy',
        'Pediatric nephrotic syndrome',
        'Periodontitis',
        'Peripheral artery disease',
        'Placental Abruption',
        'Polycystic ovary syndrome',
        'Preeclampsia',
        'Pseudoexfoliation syndrome',
        'Psoriasis',
        'Pulmonary hypertension',
        'Radiation exposure',
        'Retinopathy of prematurity',
        'Rheumatoid arthritis',
        'Salmonella',
        'Sarcoidosis',
        'Sarcopenia',
        'Schizophrenia',
        'Scleroderma',
        'Scrapie',
        'Sepsis',
        'Septic shock',
        'Sickle cell disease',
        'Sleep apnea',
        'Sleeping sickness',
        'Spinal cord injury',
        'Spondylitis',
        'Staphylococcus infection',
        'Stress',
        'Stroke',
        'Sudden infant death syndrome',
        'Systemic lupus erythematosus',
        'Thrombosis',
        'Thyroid toxicity',
        'Toxic shock',
        'Trauma',
        'Traumatic brain injury',
        'Tuberculosis',
        'Twin-twin transfusion syndrome',
        'Ulcerative colitis',
        'Urinary tract infection',
        'Viral infection',
        'Vision Loss',
        'Vitamin A deficiency',
        'VLCAD deficiency',
        'White-nose syndrome',
        'Wilson disease',
        'Yellow fever',
        'Zinc deficiency'
        ] = '',
    KEGG_ID: str = '',
    REFMET_NAME: str = ''
) -> str:
    f"""Make a call to {context} Metabolomic REST endpoint to fetch data."""    
    baseURL = "https://www.metabolomicsworkbench.org/rest"
    endpoint = f"{baseURL}/{context}/{ANALYSIS_TYPE};{POLARITY};{CHROMATOGRAPHY};{SPECIES};{SAMPLE_SOURCE};{DISEASE};{KEGG_ID};{REFMET_NAME}"
    async with aiohttp.ClientSession() as session:
        async with session.get(endpoint) as response:
            if response.ok:
                try:
                    data = await response.json()
                except:
                    data = await response.text()
                return data
            else:
                print(f"Error: {response.status}")
                return None

metstat_agent = FunctionAgent(
    name=f"{context.title()} Agent",
    description=(
        "Take a user plain language question, translate it appropriately into Metabolomics Workbench REST API endpoint keywords, call the API to get data, "
        f"and use the data to respond. Specializes in the {context} context area of the API. The 'metstat' context is a summary statistics tool that helps "
        "provide analsis and summary information on experimental datasets in the National Metabolomics Data Repository. It allows searching and summarizing "
        "data across multiple parameters and enables comparison across different experimental conditions. This agent is should be used if query is asking for study "
        "information and provides information about any or all of the following criteria: analysis type, polarity, chromatography, species, sample source, "
        "disease, KEGG ID, and or RefMet name."
    ),
    system_prompt=(
        f"You are an expert on the Metabolomics Workbench data source, specifically the {context} context of the REST API. Do not use outside knowledge.\n"
        ""
        "Step 1: Determine if the user is asking a follow up question about about data you've already retrieved. "
        "If your memory provides enough detail then stop immediately and respond directly to the user. Do NOT proceed to the remaining steps.\n"
        "Step 2: If you cannot answer the question using memory then translate the plain language user query into appropriate function arguments " 
        "to fetch data using the 'call_metstat_endpoint' tool. Use the retrieved data to and answer the query.\n"
        "If clarification is needed from the user be then ask for clarification. If you have made ANY corrections to the user's query " 
        "mention that in your response.\n"
    ),
    tools=[call_metstat_endpoint],
    can_hand_off_to=["Compound Agent", "Gene Agent", "Moverz Agent", "Protein Agent", "Refmet Agent", "Study Agent", "Metabolomics RAG Agent"]
)
