import data_sources.metabolomics_workbench.mwb.api_validation_input_output as io_validation
import data_sources.metabolomics_workbench.mwb.api_validation_permutation as validation
from llama_index.core.agent.workflow import FunctionAgent
from typing import Literal, Annotated
from workflow_config.default_settings import Settings
from .tools import call_rest_endpoint

#
# MWB sub-agent specializing in one of seven context areas of the MWB REST API
#

context = "refmet"

# Annotated tool specifically for formulating a refmet endpoint
def endpoint_kwargs(
    input_item: Annotated[
        Literal["all", "match", "name", "inchi_key", "regno", "pubchem_cid", "formula", "main_class", "sub_class"], 
        """One of all | match | name | inchi_key | regno | pubchem_cid | formula | main_class | sub_class.
        all: Retrieves all available data in JSON format for all the entries in the RefMet. The rest of the input and output parameters are not required.
        match: Converts the input value to standardized RefMet nomenclature (where possible)."""
    ],
    input_value: Annotated[
        str, 
        "An appropriate input value for given the input_item."
    ],
    output_item: Annotated[
        str, 
        """Either any of the following:
        name:
        sys_name:
        synonyms:
        regno:
        pubchem_cid:
        inchi_key:
        exactmass:
        formula:
        main_class:
        sub_class:  
        
        Or multiple output items separated by commas with no spaces. For example - name,formula,exactmass."""
    ],
    output_format: Annotated[
        Literal["txt", "json"], 
        "Return format of data. Can be one of the following: txt | json. If unsure use json."
    ] = "json"
) -> str:
    f"""Function to validate keywords needed to construct a valid REST API URL path to retrieve {context} context data from the Metabolomics Workbench website."""
    return f"{{'context': {context}, 'input_item': {input_item}, 'input_value': {input_value}, 'output_item': {output_item}, 'output_format': {output_format}}}"


refmet_agent = FunctionAgent(
    name=f"{context.title()} Agent",
    description=(
        "Take a user plain language question, translate it appropriately into Metabolomics Workbench REST API endpoint keywords, call the API to get data, "
        f"and use the data to respond. Specializes in the {context} context area of the API. The 'refmet' context refers to a standardized reference nomenclature for both "
        "discrete metabolite structures and metabolite species identified by spectroscopic techniques in metabolomics experiments. This is an essential prerequisite for the "
        "ability to compare and contrast metabolite data across different experiments and studies. The use of identifiers such as PubChem compound IDs and InChiKeys offers "
        "only a partial solution because these identifiers will vary depending on parameters such as the salt form and degree of stereochemical detail. In addition, many "
        "metabolite species, especially lipids, are not reported by MS methods as discrete structures but rather as isobaric mixtures (such as PC(34:1) and TG(54:2)). To this "
        "end, a list of over 160,000 names from a set of over 800 MS and NMR studies on the Metabolomics Workbench has been used as a starting point to generate a highly curated "
        "analytical chemistry-centric list of common names for metabolite structures and isobaric species. Additionally, the vast majority of these names have been linked to a "
        "metabolite classification system using a combination of LIPID MAPS and ClassyFire classification methods. A name-conversion user interface is provided where users can "
        "submit a list of metabolite names and map them to the corresponding Refmet names. This is a work-in-progress with the caveat that many metabolite names generated by "
        "metabolomics experiments will not currently map to RefMet identifiers. Nevertheless, RefMet has the ability to greatly increase the data-sharing potential of metabolomics "
        "experiments and facilitate 'meta-analysis' and systems biology objectives for the majority of commonly encountered metabolite species. This context provides access to many "
        "structural features including InChIKey, exact mass, formula common and systematic names, chemical classification and cross-references to other database."
    ),
    system_prompt=(
        f"You are an expert on the Metabolomics Workbench data source, specifically the {context} context of the REST API. Do not use outside knowledge.\n"
        ""
        "Step 1: Determine if the user is asking a follow up question about about data you've already retrieved. "
        "If your memory provides enough detail then stop immediately and respond directly to the user. Do NOT proceed to the remaining steps.\n"
        "Step 2: If you cannot answer the question using memory then use the following context: \n"
        f"{io_validation.refmet}"
        "and the 'endpoint_kwargs' tool to translate the plain language user query into appropriate endpoint keywords.\n"
        ""
        "Step 3: You must verify the output of 'endpoint_kwargs' against the following criteria and confirm for correctness:\n"
        f"{validation.refmet}"
        ""
        "Step 4: If the criteria in Step 3 is met then use the tool 'call_rest_endpoint' to fetch data and answer the query. "
        "If clarification is needed from the user be then ask for clarification. If you have made ANY corrections to the user's query " 
        "mention that in your response.\n"
        "Step 6: If the criteria in Step 3 is violated then restart at Step 1, but reconsider the arguments passed to 'endpoint_kwargs' or "
        "if clarification is needed from the user be then ask for clarification but be direct.\n"
    ),
    tools=[endpoint_kwargs, call_rest_endpoint],
    can_hand_off_to=["Compound Agent", "Gene Agent", "Moverz Agent", "Protein Agent", "Refmet Agent", "Study Agent", "Metabolomics RAG Agent"]
)