#
# MWB REST API Permutations of valid endpoints. Used for validation before API call.
# API broken up into seven context areas, not all have a permutation table. 
# See https://metabolomicsworkbench.org/tools/MWRestAPIv1.1.pdf for more detail
#

study  = """
| Match           | Input_name                               | Output_name           | Output_fields                                                                                                                                                                             |
|-----------------|------------------------------------------|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| exact match     | metabolite_id                            | all (ignored)         | metabolite_id,metabolite_name,refmet_name,pubchem_id,other_id,other_id_type,kegg_id,ri,ri_type,moverz_quant                                                                               |
| substring match | study_id,study_title,institute,last_name | number_of_metabolites | study_id,analysis_id,num_metabolites,analysis_display,study_title                                                                                                                         |
| substring match | study_id,study_title,institute,last_name | summary               | study_id,study_title,study_type,institute,department,last_name,first_name,email,phone,submit_date,study_summary,subject_species                                                           |
| substring match | study_id,study_title,institute,last_name | factors               | study_id,local_sample_id,subject_type,factors                                                                                                                                             |
| substring match | study_id,study_title,institute,last_name | analysis              | study_id,analysis_id,analysis_summary,analysis_type,ms_instrument_name,ms_instrument_type,ms_type,ion_mode,nmr_instrument_type,nmr_experiment_type,nmr_spectrometer_frequency,nmr_solvent |
| exact match     | study_id,analysis_id                     | metabolites           | study_id,analysis_id,analysis_summary,metabolite_name,refmet_name,pubchem_id,other_id,other_id_type                                                                                       |
| exact match     | study_id,analysis_id                     | data                  | study_id,analysis_id,analysis_summary,metabolite_name,metabolite_id,refmet_name,units,local_sample_id,measured_value                                                                      |
| exact match     | study_id,analysis_id                     | mwtab                 | mwtab                                                                                                                                                                                     |
| substring match | study_id,study_title,institute,last_name | species               | study_id,subject_species,species_common                                                                                                                                                   |
| substring match | study_id,study_title,institute,last_name | source                | study_id,source                                                                                                                                                                           |
| substring match | study_id,study_title,institute,last_name | disease               | study_id,disease                                                                                                                                                                          |
| NONE            | study_id (ignored)                       | untarg_studies        | study_id,analysis_id,analysis_display,study_title,subject_species,institute                                                                                                               |
| exact match     | analysis_id                              | untarg_factors        | factors                                                                                                                                                                                   |
| exact match     | analysis_id                              | untarg_data           | data table                                                                                                                                                                                |
| exact match     | analysis_id                              | datatable             | Tab-delimited table of metabolite measurements                                                                                                                                            |
| exact match     | kegg_id                                  | data                  | Refmet_name,kegg_id,study_id                                                                                                                                                              |
"""

compound  = """
| Match       | Input_name                                                                                  | Output_name                                                                                                                        | Output_fields                                                                                                                                                       |
| ----------- | ------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| exact match | regno,formula,inchi_key,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id,smiles,abbrev | all                                                                                                                                | regno,formula,exactmass,inchi_key,name,sys_name,smiles,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id                                                        |
| exact match | regno,formula,inchi_key,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id,smiles,abbrev | *Any, some or all of: regno,formula,exactmass,inchi_key,name,sys_name,smiles,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id | Any, some or all of: regno,formula,exactmass,inchi_key,name,sys_name,smiles,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id                                   |
| exact match | regno,formula,inchi_key,lm_id,pubchem_cid,hmdb_id,kegg_id,chebi_id,metacyc_id               | classification                                                                                                                     | regno,name,sys_name,cf_superclass,cf_class,cf_subclass,cf_direct_parent,cf_alternative_parents,lm_category,lm_main_class,smiles,abbrev,lm_sub_class,lm_class_level4 |
| exact match | regno                                                                                       | molfile                                                                                                                            | Downloadable molfile (text)                                                                                                                                         |
| exact match | regno                                                                                       | sdf                                                                                                                                | Downloadable sd file (text)                                                                                                                                         |
| exact match | regno                                                                                       | png                                                                                                                                | PNG image of compound                                                                                                                                               |
"""

refmet  = """
| Match       | Input_name                                                    | Output_name                                                                                                     | Output_fields                                                                                                  |
| ----------- | ------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| exact match | name,regno,pubchem_cid,inchi_key,formula,main_class,sub_class | all                                                                                                             | name,sys_name,synonyms,regno,pubchem_cid,inchi_key,exactmass,formula,main_class,sub_class                      |
| exact match | name,regno,pubchem_cid,inchi_key,formula,main_class,sub_class | *Any, some or all of: name,sys_name,synonyms,regno,pubchem_cid,inchi_key,exactmass,formula,main_class,sub_class | Any, some or all of: name,sys_name,synonyms,regno,pubchem_cid,inchi_key,exactmass,formula,main_class,sub_class |
| exact match | match                                                         | IGNORED                                                                                                         | name,formula,exactmass,main_class,sub_class                                                                    |
| exact match | classification                                                | IGNORED                                                                                                         | Name, super_class,main_class,sub_class for all RefMet species                                                  |
"""

gene  = """
| Match                                    | Input_name                                 | Output_name                                                                                                                                   | Output_fields                                                                                                                                                  |
| ---------------------------------------- | ------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| exact match, partial match for gene_name | mgp_id,gene_id,gene_name,gene_symbol,taxid | all                                                                                                                                           | mgp_id,gene_id,gene_name,gene_symbol,gene_synonyms,alt_names,chromosome,map_location,summary,taxid,common species name,latin species name                      |
| exact match, partial match for gene_name | mgp_id,gene_id,gene_name,gene_symbol,taxid | *Any, some or all of: mgp_id,gene_id,gene_name,gene_symbol,gene_synonyms,alt_names,chromosome,map_location,summary,taxid,species,species_long | Any, some or all of: mgp_id,gene_id,gene_name,gene_symbol,gene_synonyms,alt_names,chromosome,map_location,summary,taxid,common species name,latin species name |
"""

protein  = """
| Match                                                  | Input_name                                                                                                    | Output_name                                                                                                                                                                            | Output_fields                                                                                                                                                                         |
| ------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| exact match, partial match for gene_name, protein_name | mgp_id,gene_id,gene_name,gene_symbol,taxid,mrna_id,refseq_id,protein_gi,uniprot_id,protein_entry,protein_name | all                                                                                                                                                                                    | mgp_id,gene_id,gene_name,gene_symbol,taxid,species,species_long,mrna_id,refseq_id,protein_gi,uniprot_id,protein_entry,protein_name,seqlength,seq,is_identical_to                      |
| exact match, partial match for gene_name, protein_name | mgp_id,gene_id,gene_name,gene_symbol,taxid,mrna_id,refseq_id,protein_gi,uniprot_id,protein_entry,protein_name | *Any, some or all of: mgp_id,gene_id,gene_name,gene_symbol,taxid,species,species_long,mrna_id,refseq_id,protein_gi,uniprot_id,protein_entry,protein_name,seqlength,seq,is_identical_to | Any, some or all of: mgp_id,gene_id,gene_name,gene_symbol,taxid,species,species_long,mrna_id,refseq_id,protein_gi,uniprot_id,protein_entry,protein_name,seqlength,seq,is_identical_to |
"""
